"""Core tracker schema — creates the tracker's own tables in Postgres.

Creates only. Nothing here reads, moves or alters anything in notes.db: the
existing app keeps its SQLite stores exactly as they are, and these tables start
empty. See docs/tracker/DESIGN.md.


Revision ID: 07f5cd3555e2
Revises: 
Created: 2026-08-06 10:33:29.838146+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '07f5cd3555e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), server_default='human', nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=True),
    sa.Column('from_value', sa.Text(), nullable=True),
    sa.Column('to_value', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_at', 'events', [sa.text('at DESC')], unique=False)
    op.create_index('ix_events_batch', 'events', ['batch_id'], unique=False)
    op.create_index('ix_events_entity', 'events', ['entity_type', 'entity_id', 'at'], unique=False)
    op.create_index('ix_events_field', 'events', ['field', sa.text('at DESC')], unique=False)
    op.create_table('field_defs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind in ('number','text','longtext','select','multiselect','user','date','checkbox','url')", name=op.f('ck_field_defs_kind_known')),
    sa.CheckConstraint('key = lower(key)', name=op.f('ck_field_defs_key_lower')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_defs')),
    sa.UniqueConstraint('key', name=op.f('uq_field_defs_key'))
    )
    op.create_table('issue_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), server_default='', nullable=False),
    sa.Column('colour', sa.String(length=9), server_default='#8b949e', nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_types')),
    sa.UniqueConstraint('key', name=op.f('uq_issue_types_key'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=8), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('issue_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('key = upper(key)', name=op.f('ck_projects_key_upper')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('key', name=op.f('uq_projects_key'))
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('colour', sa.String(length=9), server_default='#8b949e', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category in ('todo','in_progress','done')", name=op.f('ck_statuses_category_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses')),
    sa.UniqueConstraint('key', name=op.f('uq_statuses_key'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.Text(), server_default='', nullable=False),
    sa.Column('avatar', sa.Text(), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('field_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('issue_type_id', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_defs.id'], name=op.f('fk_field_usage_field_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], name=op.f('fk_field_usage_issue_type_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_field_usage_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_usage')),
    sa.UniqueConstraint('field_id', 'project_id', 'issue_type_id', name='uq_field_usage_scope')
    )
    op.create_table('issues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('issue_type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=16), server_default='medium', nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('rank', sa.String(length=64), server_default='', nullable=False),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('estimate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], name=op.f('fk_issues_issue_type_id')),
    sa.ForeignKeyConstraint(['parent_id'], ['issues.id'], name=op.f('fk_issues_parent_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_issues_project_id')),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_issues_status_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues')),
    sa.UniqueConstraint('key', name=op.f('uq_issues_key'))
    )
    op.create_index('ix_issues_assignee', 'issues', ['assignee_id'], unique=False)
    op.create_index('ix_issues_board', 'issues', ['project_id', 'status_id', 'rank'], unique=False)
    op.create_index('ix_issues_custom', 'issues', ['custom'], unique=False, postgresql_using='gin')
    op.create_index('ix_issues_parent', 'issues', ['parent_id'], unique=False)
    op.create_index('ix_issues_updated', 'issues', [sa.text('updated_at DESC')], unique=False)
    op.create_table('project_issue_types',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('issue_type_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], name=op.f('fk_project_issue_types_issue_type_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_issue_types_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'issue_type_id', name=op.f('pk_project_issue_types'))
    )
    op.create_table('views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('shared', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('filter', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('group_by', sa.String(length=32), server_default='status', nullable=False),
    sa.Column('renderer', sa.String(length=16), server_default='columns', nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('sort', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('wip_limits', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("renderer in ('columns','table','timeline','swimlanes')", name=op.f('ck_views_renderer_known')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_views_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_views'))
    )
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('shipped_status_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shipped_status_id'], ['statuses.id'], name=op.f('fk_workflows_shipped_status_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_comments_issue_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_issue', 'comments', ['issue_id', 'created_at'], unique=False)
    op.create_table('project_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('issue_type_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], name=op.f('fk_project_workflows_issue_type_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_workflows_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_project_workflows_workflow_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_workflows')),
    sa.UniqueConstraint('project_id', 'issue_type_id', name='uq_project_workflows_scope')
    )
    op.create_table('transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('from_status_id', sa.Integer(), nullable=True),
    sa.Column('to_status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('validators', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('post_actions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['from_status_id'], ['statuses.id'], name=op.f('fk_transitions_from_status_id')),
    sa.ForeignKeyConstraint(['to_status_id'], ['statuses.id'], name=op.f('fk_transitions_to_status_id')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_transitions_workflow_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transitions'))
    )
    op.create_index('ix_transitions_lookup', 'transitions', ['workflow_id', 'from_status_id'], unique=False)
    op.create_table('workflow_statuses',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_workflow_statuses_status_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_statuses_workflow_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id', 'status_id', name=op.f('pk_workflow_statuses'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_statuses')
    op.drop_index('ix_transitions_lookup', table_name='transitions')
    op.drop_table('transitions')
    op.drop_table('project_workflows')
    op.drop_index('ix_comments_issue', table_name='comments')
    op.drop_table('comments')
    op.drop_table('workflows')
    op.drop_table('views')
    op.drop_table('project_issue_types')
    op.drop_index('ix_issues_updated', table_name='issues')
    op.drop_index('ix_issues_parent', table_name='issues')
    op.drop_index('ix_issues_custom', table_name='issues', postgresql_using='gin')
    op.drop_index('ix_issues_board', table_name='issues')
    op.drop_index('ix_issues_assignee', table_name='issues')
    op.drop_table('issues')
    op.drop_table('field_usage')
    op.drop_table('users')
    op.drop_table('statuses')
    op.drop_table('projects')
    op.drop_table('issue_types')
    op.drop_table('field_defs')
    op.drop_index('ix_events_field', table_name='events')
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_index('ix_events_batch', table_name='events')
    op.drop_index('ix_events_at', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
