"""Board columns: a column is a container of statuses, not a status.

Autogenerated, then given a backfill by hand. Two new tables plus one column
per existing workflow status, in the order the board already had — so every
board looks exactly the same after this as before it, and the new shape is only
visible once somebody groups two statuses together.

Tracker Postgres only.
"""
from alembic import op
import sqlalchemy as sa


revision = '0321667e2ea6'
down_revision = '5bbfa4afc079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_board_columns_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_columns'))
    )
    op.create_index('ix_board_columns_project', 'board_columns', ['project_id', 'position'], unique=False)
    op.create_table('board_column_statuses',
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['board_columns.id'], name=op.f('fk_board_column_statuses_column_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_board_column_statuses_status_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('column_id', 'status_id', name=op.f('pk_board_column_statuses'))
    )
    op.create_index('ix_board_column_statuses_status', 'board_column_statuses', ['status_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: one column per status the board already shows, same name, same
    # order. A migration that changes the model should not change the screen.
    op.execute("""
        INSERT INTO board_columns (project_id, name, position)
        SELECT pw.project_id, s.name, ws.position
          FROM project_workflows pw
          JOIN workflow_statuses ws ON ws.workflow_id = pw.workflow_id
          JOIN statuses s ON s.id = ws.status_id
         WHERE pw.issue_type_id IS NULL
    """)
    op.execute("""
        INSERT INTO board_column_statuses (column_id, status_id, position)
        SELECT bc.id, ws.status_id, 0
          FROM board_columns bc
          JOIN project_workflows pw
            ON pw.project_id = bc.project_id AND pw.issue_type_id IS NULL
          JOIN workflow_statuses ws
            ON ws.workflow_id = pw.workflow_id AND ws.position = bc.position
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_board_column_statuses_status', table_name='board_column_statuses')
    op.drop_table('board_column_statuses')
    op.drop_index('ix_board_columns_project', table_name='board_columns')
    op.drop_table('board_columns')
    # ### end Alembic commands ###
