"""Automations: rules, their job queue, and the audit log.

Autogenerated from schema.py. Additive only — four new tables and their
indexes. Tracker Postgres only; notes.db is a different database in a
different engine and no migration here can reach it.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '04398070dec3'
down_revision = '7f15cb6ef615'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_worker_state'))
    )
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('run_as', sa.String(length=20), server_default='automation', nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('disabled_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("run_as in ('automation','actor')", name=op.f('ck_automation_rules_run_as_known')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_automation_rules_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_rules'))
    )
    op.create_table('automation_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=True),
    sa.Column('entity_type', sa.String(length=20), server_default='issue', nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state in ('pending','running','done','failed','skipped')", name=op.f('ck_automation_jobs_state_known')),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], name=op.f('fk_automation_jobs_rule_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_jobs')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_automation_jobs_dedupe_key'))
    )
    op.create_index('ix_automation_jobs_issue', 'automation_jobs', ['issue_id', 'state'], unique=False)
    op.create_index('ix_automation_jobs_queue', 'automation_jobs', ['state', 'scheduled_at'], unique=False)
    op.create_table('automation_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('condition_result', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('dry_run', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome in ('ran','skipped','failed')", name=op.f('ck_automation_runs_outcome_known')),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], name=op.f('fk_automation_runs_rule_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_runs'))
    )
    op.create_index('ix_automation_runs_rule', 'automation_runs', ['rule_id', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automation_runs_rule', table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index('ix_automation_jobs_queue', table_name='automation_jobs')
    op.drop_index('ix_automation_jobs_issue', table_name='automation_jobs')
    op.drop_table('automation_jobs')
    op.drop_table('automation_rules')
    op.drop_table('worker_state')
    # ### end Alembic commands ###
