"""Teams, the two priorities, urgency provenance, and pauses.

Autogenerated. Additive: three tables and five columns, every one nullable or
defaulted, so existing issues stay valid — no team means free-for-all, which is
a real state rather than a gap. Tracker Postgres only.
"""
from alembic import op
import sqlalchemy as sa


revision = '5bbfa4afc079'
down_revision = '8a38a980b5db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('colour', sa.String(length=9), server_default='#5b8cff', nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('key', name=op.f('uq_teams_key'))
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('craft', sa.String(length=16), server_default='dev', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name=op.f('pk_team_members'))
    )
    op.create_index('ix_team_members_user', 'team_members', ['user_id'], unique=False)
    op.create_table('issue_pauses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('paused_by', sa.Integer(), nullable=True),
    sa.Column('paused_for_issue_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_pauses_issue_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paused_for_issue_id'], ['issues.id'], name=op.f('fk_issue_pauses_paused_for_issue_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_pauses'))
    )
    op.create_index('ix_issue_pauses_for', 'issue_pauses', ['paused_for_issue_id'], unique=False)
    op.create_index('ix_issue_pauses_open', 'issue_pauses', ['issue_id', 'resumed_at'], unique=False)
    op.add_column('issues', sa.Column('plan_priority', sa.String(length=16), server_default='medium', nullable=False))
    op.add_column('issues', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('urgent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('issues', sa.Column('urgent_by', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('urgent_reason', sa.Text(), server_default='', nullable=False))
    op.create_index('ix_issues_assignee_queue', 'issues', ['assignee_id', 'priority', 'rank'], unique=False)
    op.create_index('ix_issues_team_queue', 'issues', ['team_id', 'priority', 'rank'], unique=False)
    op.create_foreign_key(op.f('fk_issues_team_id'), 'issues', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_issues_team_id'), 'issues', type_='foreignkey')
    op.drop_index('ix_issues_team_queue', table_name='issues')
    op.drop_index('ix_issues_assignee_queue', table_name='issues')
    op.drop_column('issues', 'urgent_reason')
    op.drop_column('issues', 'urgent_by')
    op.drop_column('issues', 'urgent_at')
    op.drop_column('issues', 'team_id')
    op.drop_column('issues', 'plan_priority')
    op.drop_index('ix_issue_pauses_open', table_name='issue_pauses')
    op.drop_index('ix_issue_pauses_for', table_name='issue_pauses')
    op.drop_table('issue_pauses')
    op.drop_index('ix_team_members_user', table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('teams')
    # ### end Alembic commands ###
