"""Issue links: blocked by, duplicates, relates to.

Autogenerated. One additive table plus its indexes. Directional and stored
once — A blocks B is a single row, and B works out that it is blocked by A —
so the two directions cannot disagree. Tracker Postgres only.
"""
from alembic import op
import sqlalchemy as sa


revision = '6e9ca8f3ed0a'
down_revision = '0321667e2ea6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_id <> target_id', name=op.f('ck_issue_links_not_itself')),
    sa.ForeignKeyConstraint(['source_id'], ['issues.id'], name=op.f('fk_issue_links_source_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['issues.id'], name=op.f('fk_issue_links_target_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_links')),
    sa.UniqueConstraint('source_id', 'target_id', 'kind', name='uq_issue_links_source_id')
    )
    op.create_index('ix_issue_links_source', 'issue_links', ['source_id'], unique=False)
    op.create_index('ix_issue_links_target', 'issue_links', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_issue_links_target', table_name='issue_links')
    op.drop_index('ix_issue_links_source', table_name='issue_links')
    op.drop_table('issue_links')
    # ### end Alembic commands ###
