"""Releases: what ships, when, and what is in it.

Autogenerated from schema.py. Additive only — five new tables and their
indexes, nothing altered and nothing dropped. As with every migration here,
this touches the tracker's Postgres database only; notes.db is a different
database in a different engine and no migration in this directory can reach it.
"""
from alembic import op
import sqlalchemy as sa


revision = '7f15cb6ef615'
down_revision = '0002_event_batch_seq'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('repo', sa.Text(), server_default='', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_components')),
    sa.UniqueConstraint('key', name=op.f('uq_components_key'))
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), server_default='standard', nullable=False),
    sa.Column('state', sa.String(length=16), server_default='planning', nullable=False),
    sa.Column('cycle_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('notes_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state in ('planning','in_progress','shipped','cancelled')", name=op.f('ck_releases_state_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_releases'))
    )
    op.create_index('ix_releases_state', 'releases', ['state', 'planned_at'], unique=False)
    op.create_table('release_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_release_actions_release_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_actions'))
    )
    op.create_index('ix_release_actions_release', 'release_actions', ['release_id', 'position'], unique=False)
    op.create_table('release_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Text(), server_default='', nullable=False),
    sa.Column('state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("state in ('pending','shipped','skipped')", name=op.f('ck_release_artifacts_state_known')),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_release_artifacts_component_id')),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_release_artifacts_release_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_artifacts')),
    sa.UniqueConstraint('release_id', 'component_id', name='uq_release_artifacts_release_id')
    )
    op.create_index('ix_release_artifacts_release', 'release_artifacts', ['release_id'], unique=False)
    op.create_table('release_issues',
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_release_issues_issue_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_release_issues_release_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('release_id', 'issue_id', name=op.f('pk_release_issues'))
    )
    op.create_index('ix_release_issues_issue', 'release_issues', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_release_issues_issue', table_name='release_issues')
    op.drop_table('release_issues')
    op.drop_index('ix_release_artifacts_release', table_name='release_artifacts')
    op.drop_table('release_artifacts')
    op.drop_index('ix_release_actions_release', table_name='release_actions')
    op.drop_table('release_actions')
    op.drop_index('ix_releases_state', table_name='releases')
    op.drop_table('releases')
    op.drop_table('components')
    # ### end Alembic commands ###
