"""Where each status sits on the workflow diagram.

Autogenerated. One column with a default of {}, meaning "lay it out
automatically" — so every existing workflow keeps working and nothing needs
backfilling. Tracker Postgres only.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8a38a980b5db'
down_revision = 'ffb93e7e7e16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'layout')
    # ### end Alembic commands ###
