"""Who can see a project.

Autogenerated. Additive: one table and one column with a default, so every
existing project stays visible to everyone and nothing needs backfilling.
Tracker Postgres only.
"""
from alembic import op
import sqlalchemy as sa


revision = 'ffb93e7e7e16'
down_revision = '04398070dec3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('user','tag')", name=op.f('ck_project_access_kind_known')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_access_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_access')),
    sa.UniqueConstraint('project_id', 'kind', 'value', name='uq_project_access_project_id')
    )
    op.add_column('projects', sa.Column('visibility', sa.String(length=16), server_default='everyone', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'visibility')
    op.drop_table('project_access')
    # ### end Alembic commands ###
